apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: inngress
spec:
  rules:
  - host: localhost
    http:
      paths:
      - backend:
          serviceName: simple-node-app
          servicePort: 3000
